# Generated by Django 6.0.7 on 2026-09-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_color_product_is_active_product_size_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('sku', ''), _negated=True), name='variant_sku_not_blank'),
        ),
    ]
