# Generated by Django 6.0.7 on 2026-09-24 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariant_variant_sku_not_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # A reverted deploy (8c6317d -> 0de71a6) left behind an old-schema
        # catalog_importjob table plus an orphan django_migrations row for the
        # now-deleted "0007_importjob" migration. Drop both so the CreateModel
        # below can run; no-ops on fresh or already-migrated databases.
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS catalog_importjob",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DELETE FROM django_migrations WHERE app = 'catalog' AND name = '0007_importjob'",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('product', 'variant', 'order', 'id')},
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, help_text='Stable product identifier for bulk imports (e.g., LSD001)', max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='catalog.productvariant'),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('READY', 'Ready for Import'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with Errors'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='UPLOADED', max_length=30)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('created_products', models.PositiveIntegerField(default=0)),
                ('updated_products', models.PositiveIntegerField(default=0)),
                ('created_variants', models.PositiveIntegerField(default=0)),
                ('updated_variants', models.PositiveIntegerField(default=0)),
                ('uploaded_images', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('import_status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validation_results', models.JSONField(blank=True, default=dict)),
                ('import_results', models.JSONField(blank=True, default=dict)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='catalog_imp_status_77888b_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='catalog_imp_uploade_595b94_idx')],
            },
        ),
    ]
