# Generated by Django 6.0.7 on 2026-09-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_productimage_options_product_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='package_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='importjob',
            name='package_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importjob',
            name='package_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='processing_lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='processing_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='importjob',
            name='validation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
