from django.urls import path

from .views import (AdminCategoryCreateView, AdminNotificationReadView,
                    AdminNotificationsPresentView, AdminNotificationsReadAllView,
                    AdminNotificationsView, AdminProductArchiveView,
                    AdminProductCreateView, AdminProductUpdateView,
                    AdminStockAdjustmentView, AdminUnreadNotificationsView,
                    BulkImportCancelView, BulkImportConfirmView,
                    BulkImportHistoryView, BulkImportPreviewView,
                    BulkImportProcessView, BulkImportReportView,
                    BulkImportStatusView, BulkImportTemplateView,
                    BulkImportUploadView, BulkImportValidateView,
                    ExpireReservationsView)


urlpatterns = [
    path('admin/products', AdminProductCreateView.as_view(),
         name='admin-product-create'),
    path('admin/products/<uuid:product_id>',
         AdminProductUpdateView.as_view(), name='admin-product-update'),
    path('admin/products/<uuid:product_id>/archive',
         AdminProductArchiveView.as_view(), name='admin-product-archive'),
    path('admin/categories', AdminCategoryCreateView.as_view(),
         name='admin-category-create'),
    path('admin/inventory/<uuid:variant_id>',
         AdminStockAdjustmentView.as_view(), name='admin-stock-adjustment'),
    path('admin/maintenance/expire-reservations',
         ExpireReservationsView.as_view(), name='admin-expire-reservations'),
    path('admin/notifications',
         AdminNotificationsView.as_view(), name='admin-notifications-api'),
    path('admin/notifications/unread',
         AdminUnreadNotificationsView.as_view(), name='admin-notifications-unread-api'),
    path('admin/notifications/presented',
         AdminNotificationsPresentView.as_view(), name='admin-notifications-presented-api'),
    path('admin/notifications/<uuid:notification_id>/read',
         AdminNotificationReadView.as_view(), name='admin-notification-read-api'),
    path('admin/notifications/read-all',
         AdminNotificationsReadAllView.as_view(), name='admin-notifications-read-all-api'),
    path('admin/bulk-import/template',
         BulkImportTemplateView.as_view(), name='admin-bulk-import-template'),
    path('admin/bulk-import/upload',
         BulkImportUploadView.as_view(), name='admin-bulk-import-upload'),
    path('admin/bulk-import/history',
         BulkImportHistoryView.as_view(), name='admin-bulk-import-history'),
    path('admin/bulk-import/<uuid:job_id>/validate',
         BulkImportValidateView.as_view(), name='admin-bulk-import-validate'),
    path('admin/bulk-import/<uuid:job_id>/preview',
         BulkImportPreviewView.as_view(), name='admin-bulk-import-preview'),
    path('admin/bulk-import/<uuid:job_id>/confirm',
         BulkImportConfirmView.as_view(), name='admin-bulk-import-confirm'),
    path('admin/bulk-import/<uuid:job_id>/process',
         BulkImportProcessView.as_view(), name='admin-bulk-import-process'),
    path('admin/bulk-import/<uuid:job_id>/status',
         BulkImportStatusView.as_view(), name='admin-bulk-import-status'),
    path('admin/bulk-import/<uuid:job_id>/cancel',
         BulkImportCancelView.as_view(), name='admin-bulk-import-cancel'),
    path('admin/bulk-import/<uuid:job_id>/report',
         BulkImportReportView.as_view(), name='admin-bulk-import-report'),
]
