# Generated by Django 6.0.7 on 2026-09-26 08:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0009_alter_productimage_image_url'),
        ('orders', '0003_order_coupon_code_order_discount_minor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('percentage', 'Percentage discount'), ('fixed', 'Fixed amount discount'), ('free_shipping', 'Free shipping'), ('buy_x_get_y', 'Buy X Get Y free'), ('buy_x_get_pct', 'Buy X Get % off')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('scheduled', 'Scheduled'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='draft', max_length=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount_minor', models.PositiveIntegerField(default=0)),
                ('maximum_discount_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_order_value_minor', models.PositiveIntegerField(default=0)),
                ('minimum_quantity', models.PositiveIntegerField(default=0)),
                ('qualifying_quantity', models.PositiveIntegerField(default=0)),
                ('reward_quantity', models.PositiveIntegerField(default=0)),
                ('reward_discount_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_redemptions_per_order', models.PositiveIntegerField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=60)),
                ('coupon_code_normalized', models.CharField(blank=True, db_index=True, max_length=60)),
                ('is_automatic', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit_per_customer', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=10)),
                ('stackable', models.BooleanField(default=False)),
                ('eligible_all', models.BooleanField(default=True)),
                ('sale_only', models.BooleanField(default=False)),
                ('new_only', models.BooleanField(default=False)),
                ('customer_scope', models.CharField(choices=[('all', 'Everyone'), ('new', 'New customers'), ('existing', 'Existing customers'), ('specific', 'Specific customers')], default='all', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-priority', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_links', to='catalog.category')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_categories', to='promotions.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_customers', to='promotions.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_links', to='catalog.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_products', to='promotions.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_key', models.CharField(blank=True, max_length=100)),
                ('coupon_code', models.CharField(blank=True, max_length=60)),
                ('discount_minor', models.PositiveIntegerField(default=0)),
                ('shipping_discount_minor', models.PositiveIntegerField(default=0)),
                ('voided', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_redemptions', to='orders.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.promotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-redeemed_at',),
            },
        ),
        migrations.CreateModel(
            name='PromotionVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_variants', to='promotions.promotion')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_links', to='catalog.productvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['status'], name='promotions__status_b908b5_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['coupon_code_normalized'], name='promotions__coupon__aa625f_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_automatic', 'status'], name='promotions__is_auto_aa6fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['starts_at', 'ends_at'], name='promotions__starts__1b26a0_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['-priority'], name='promotions__priorit_e61306_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='promo_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('reward_discount_percent__gte', 0), ('reward_discount_percent__lte', 100)), name='promo_reward_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='promotioncategory',
            constraint=models.UniqueConstraint(fields=('promotion', 'category'), name='unique_promo_category'),
        ),
        migrations.AddConstraint(
            model_name='promotioncustomer',
            constraint=models.UniqueConstraint(fields=('promotion', 'user'), name='unique_promo_customer'),
        ),
        migrations.AddConstraint(
            model_name='promotionproduct',
            constraint=models.UniqueConstraint(fields=('promotion', 'product'), name='unique_promo_product'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['promotion', 'voided'], name='promotions__promoti_430169_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['user'], name='promotions__user_id_c6edaa_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['order'], name='promotions__order_i_dcf5cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotionredemption',
            constraint=models.UniqueConstraint(fields=('promotion', 'order'), name='unique_promo_order'),
        ),
        migrations.AddConstraint(
            model_name='promotionvariant',
            constraint=models.UniqueConstraint(fields=('promotion', 'variant'), name='unique_promo_variant'),
        ),
    ]
