from django.urls import path

from .views import (
    ActivityExportView,
    ActivityOverviewPageView,
    AdminLandingPageView,
    AdminLoginView,
    AdminLogoutView,
    AdminNotificationsPageView,
    AdminPageView,
    AdminRegisterView,
    AdminUserInvitePageView,
    ApproveOrderPageView,
    AuditLogsPageView,
    CategoryCreatePageView,
    CategoryDeletePageView,
    CategoryEditPageView,
    ConfirmActionView,
    CustomerDetailPageView,
    DashboardView,
    ErrorCenterPageView,
    MarkAllNotificationsReadView,
    MarkNotificationReadView,
    OrderDetailPageView,
    OrderReceiptDownloadView,
    OrderReceiptRegenerateView,
    ProductArchivePageView,
    UnreadNotificationsView,
    ProductCreatePageView,
    ProductDeletePageView,
    ProductDetailPageView,
    ProductDuplicatePageView,
    ProductEditPageView,
    ProductVariantCreatePageView,
    ProductVariantDeletePageView,
    ProductVariantEditPageView,
    ProductImportPageView,
    ProductImportTemplateDownloadView,
    ProfileSettingsPageView,
    RequestTracePageView,
    SecurityCenterPageView,
    StockAdjustmentPageView,
    SystemHealthPageView,
)


urlpatterns = [
    path('landing/', AdminLandingPageView.as_view(), name='admin-landing'),
    path('login/', AdminLoginView.as_view(), name='admin-login'),
    path('logout/', AdminLogoutView.as_view(), name='admin-logout'),
    path('register/', AdminRegisterView.as_view(), name='admin-register'),
    path('', DashboardView.as_view(), name='admin-dashboard'),
    path('audit-logs/', AuditLogsPageView.as_view(), name='admin-audit-logs'),
    path('activity/', ActivityOverviewPageView.as_view(), name='admin-activity'),
    path('activity/errors/', ErrorCenterPageView.as_view(), name='admin-errors'),
    path('activity/request/<request_id>/', RequestTracePageView.as_view(),
         name='admin-request-trace'),
    path('activity/export/', ActivityExportView.as_view(),
         name='admin-activity-export'),
    path('security/', SecurityCenterPageView.as_view(), name='admin-security'),
    path('system-health/', SystemHealthPageView.as_view(),
         name='admin-system-health'),
    path('confirm/', ConfirmActionView.as_view(), name='admin-confirm-action'),
    path('products/import/', ProductImportPageView.as_view(),
         name='admin-product-import'),
    path('products/import/download-template/', ProductImportTemplateDownloadView.as_view(),
         name='admin-product-import-template'),
    path('notifications/', AdminNotificationsPageView.as_view(),
         name='admin-notifications'),
    path('notifications/unread/', UnreadNotificationsView.as_view(),
         name='admin-unread-notifications'),
    path('notifications/read-all/', MarkAllNotificationsReadView.as_view(),
         name='admin-notifications-read-all'),
    path('notifications/<uuid:notification_id>/read/', MarkNotificationReadView.as_view(),
         name='admin-notification-read'),
    path('products/', AdminPageView.as_view(),
         {'page': 'products'}, name='admin-products'),
    path('products/<uuid:product_id>/', ProductDetailPageView.as_view(),
         name='admin-product-detail'),
    path('products/new/', ProductCreatePageView.as_view(),
         name='admin-product-create'),
    path('products/<uuid:product_id>/edit/',
         ProductEditPageView.as_view(), name='admin-product-edit'),
    path('products/<uuid:product_id>/variants/new/',
         ProductVariantCreatePageView.as_view(), name='admin-variant-create'),
    path('products/<uuid:product_id>/variants/<uuid:variant_id>/edit/',
         ProductVariantEditPageView.as_view(), name='admin-variant-edit'),
    path('products/<uuid:product_id>/variants/<uuid:variant_id>/delete/',
         ProductVariantDeletePageView.as_view(), name='admin-variant-delete'),
    path('products/<uuid:product_id>/duplicate/',
         ProductDuplicatePageView.as_view(), name='admin-product-duplicate'),
    path('products/<uuid:product_id>/archive/',
         ProductArchivePageView.as_view(), name='admin-product-archive'),
    path('products/<uuid:product_id>/delete/',
         ProductDeletePageView.as_view(), name='admin-product-delete'),
    path('admin-users/', AdminPageView.as_view(),
         {'page': 'admin-users'}, name='admin-users'),
    path('admin-users/invite/', AdminUserInvitePageView.as_view(),
         name='admin-user-invite'),
    path('profile/', AdminPageView.as_view(),
         {'page': 'profile'}, name='admin-profile'),
    path('profile/settings/', ProfileSettingsPageView.as_view(),
         name='admin-profile-settings'),
    path('categories/', AdminPageView.as_view(),
         {'page': 'categories'}, name='admin-categories'),
    path('categories/new/', CategoryCreatePageView.as_view(),
         name='admin-category-create'),
    path('categories/<uuid:category_id>/edit/',
         CategoryEditPageView.as_view(), name='admin-category-edit'),
    path('categories/<uuid:category_id>/delete/',
         CategoryDeletePageView.as_view(), name='admin-category-delete'),
    path('inventory/', AdminPageView.as_view(),
         {'page': 'inventory'}, name='admin-inventory'),
    path('inventory/adjust/', StockAdjustmentPageView.as_view(),
         name='admin-stock-adjust'),
    path('orders/', AdminPageView.as_view(),
         {'page': 'orders'}, name='admin-orders'),
    path('orders/<uuid:order_id>/', OrderDetailPageView.as_view(),
         name='admin-order-detail'),
    path('orders/<uuid:order_id>/receipt/download/',
         OrderReceiptDownloadView.as_view(),
         name='admin-order-receipt-download'),
    path('orders/<uuid:order_id>/receipt/regenerate/',
         OrderReceiptRegenerateView.as_view(),
         name='admin-order-receipt-regenerate'),
    path('orders/<uuid:order_id>/approve/', ApproveOrderPageView.as_view(),
         name='admin-order-approve'),
    path('customers/', AdminPageView.as_view(),
         {'page': 'customers'}, name='admin-customers'),
    path('customers/<int:customer_id>/', CustomerDetailPageView.as_view(),
         name='admin-customer-detail'),
    path('analytics/', AdminPageView.as_view(),
         {'page': 'analytics'}, name='admin-analytics'),
    path('reports/', AdminPageView.as_view(),
         {'page': 'reports'}, name='admin-reports'),
    path('performance/', AdminPageView.as_view(),
         {'page': 'performance'}, name='admin-performance'),
]
