# Generated by Django 6.1.1 on 2026-09-25 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0009_alter_productimage_image_url'),
        ('orders', '0002_alter_order_payment_method_alter_order_status'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('email_type', models.CharField(choices=[('order_confirmation', 'Order confirmation'), ('order_confirmed', 'Order confirmed'), ('order_cancelled', 'Order cancelled'), ('order_received', 'Order received'), ('payment_success', 'Payment successful'), ('payment_failed', 'Payment failed'), ('receipt', 'Receipt'), ('welcome', 'Welcome'), ('back_in_stock', 'Back in stock'), ('admin_new_order', 'Admin: new order'), ('admin_payment_failed', 'Admin: payment failed'), ('admin_low_stock', 'Admin: low stock'), ('admin_critical_error', 'Admin: critical system error'), ('bulk_import_completed', 'Bulk import completed'), ('bulk_import_failed', 'Bulk import failed')], max_length=64)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=150)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(blank=True, default='')),
                ('template_name', models.CharField(blank=True, default='', max_length=120)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('RETRYING', 'Retrying'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('last_error', models.TextField(blank=True, default='')),
                ('related_import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='catalog.importjob')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='orders.order')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='payments.paymentintent')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-queued_at',),
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='emails_emai_status_9dc571_idx'), models.Index(fields=['email_type', '-queued_at'], name='emails_emai_email_t_66f5a4_idx'), models.Index(fields=['-queued_at'], name='emails_emai_queued__f5bb89_idx')],
                'constraints': [models.UniqueConstraint(fields=('idempotency_key',), name='uniq_emaillog_key')],
            },
        ),
    ]
