# Generated by Django 6.0.7 on 2026-09-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('order_confirmation', 'Order confirmation'), ('order_confirmed', 'Order confirmed'), ('order_cancelled', 'Order cancelled'), ('order_received', 'Order received'), ('payment_success', 'Payment successful'), ('payment_failed', 'Payment failed'), ('receipt', 'Receipt'), ('welcome', 'Welcome'), ('back_in_stock', 'Back in stock'), ('promotion_announcement', 'Promotion announcement'), ('promotion_ending_soon', 'Promotion ending soon'), ('coupon_issued', 'Coupon issued'), ('admin_new_order', 'Admin: new order'), ('admin_payment_failed', 'Admin: payment failed'), ('admin_low_stock', 'Admin: low stock'), ('admin_critical_error', 'Admin: critical system error'), ('bulk_import_completed', 'Bulk import completed'), ('bulk_import_failed', 'Bulk import failed')], max_length=64),
        ),
    ]
