# Generated by Django 6.1.1 on 2026-09-21 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0002_alter_adminnotification_category_and_more'),
        ('audit', '0002_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='audit_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='audit.auditlog'),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='event_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='resource_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='resource_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='severity',
            field=models.CharField(default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='category',
            field=models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('inventory', 'Inventory'), ('system', 'System'), ('customer', 'Customer'), ('security', 'Security')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='admin_ui_ad_recipie_905823_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['recipient', 'category', '-created_at'], name='admin_ui_ad_recipie_036135_idx'),
        ),
    ]
