# Generated by Django 6.1.1 on 2026-09-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ui', '0003_adminnotification_actor_adminnotification_audit_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='presented_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='presented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
