# Generated by Django 6.0.7 on 2026-09-23 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariant_variant_sku_not_blank'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackInStockRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_in_stock_requests', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('variant', 'email'), name='unique_back_in_stock_request')],
            },
        ),
    ]
