# Generated by Django 6.0.7 on 2026-09-21 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('failed', 'Failed')], default='generated', max_length=12)),
                ('snapshot', models.JSONField(default=dict)),
                ('pdf_key', models.CharField(blank=True, max_length=500)),
                ('pdf_url', models.URLField(blank=True)),
                ('payload_size', models.PositiveIntegerField(default=0)),
                ('amount_minor', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('gateway_reference', models.CharField(blank=True, max_length=80)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_attempts', models.PositiveIntegerField(default=0)),
                ('email_error', models.CharField(blank=True, max_length=300)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['order', 'created_at'], name='receipts_re_order_i_faf21c_idx')],
            },
        ),
    ]
