# Generated by Django 6.1.1 on 2026-09-28 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], db_index=True, default='active', max_length=12)),
                ('last_interaction_id', models.CharField(blank=True, default='', max_length=120)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AssistantInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('unanswered', 'Unanswered'), ('zero_result', 'Zero Result'), ('escalation', 'Escalation'), ('gemini_error', 'Gemini Error')], db_index=True, max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('normalized', models.CharField(db_index=True, max_length=500)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-last_seen',),
                'indexes': [models.Index(fields=['kind', '-last_seen'], name='assistant_a_kind_6d71f5_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'normalized'), name='unique_assistant_insight')],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('kind', models.CharField(choices=[('reply', 'Reply'), ('error', 'Error')], default='reply', max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('product_refs', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('unanswered', models.BooleanField(db_index=True, default=False)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantconversation')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssistantToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(db_index=True, max_length=64)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('error', 'Error'), ('timeout', 'Timeout')], db_index=True, default='ok', max_length=12)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='assistant.assistantconversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to='assistant.assistantmessage')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['user', '-created_at'], name='assistant_a_user_id_1a8b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['status', '-updated_at'], name='assistant_a_status_d8cb5c_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='assistant_a_convers_6c399e_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['created_at'], name='assistant_a_created_5b03d4_idx'),
        ),
        migrations.AddIndex(
            model_name='assistanttoolcall',
            index=models.Index(fields=['conversation', 'created_at'], name='assistant_a_convers_6c1a72_idx'),
        ),
        migrations.AddIndex(
            model_name='assistanttoolcall',
            index=models.Index(fields=['tool_name', 'created_at'], name='assistant_a_tool_na_289fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='assistanttoolcall',
            index=models.Index(fields=['status', 'created_at'], name='assistant_a_status_91d500_idx'),
        ),
    ]
