"""
Django settings for botique_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY',
                       'django-insecure-local-development-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,testserver').split(',')
    if host.strip()
]
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS + ['testserver']))

PAYMENT_WEBHOOK_SECRET = os.getenv(
    'PAYMENT_WEBHOOK_SECRET', 'local-development-payment-secret')
MPESA_CALLBACK_SECRET = os.getenv(
    'MPESA_CALLBACK_SECRET', 'local-development-mpesa-secret')
FRONTEND_ORIGIN = os.getenv(
    'FRONTEND_ORIGIN',
    'http://localhost:3000'
).rstrip('/')
CORS_ALLOWED_ORIGINS = [
    FRONTEND_ORIGIN,
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept', 'authorization', 'content-type', 'origin', 'x-csrftoken',
    'x-requested-with', 'x-cart-id',
]

# ---------------------------------------------------------------------------
# Store branding (used by receipt PDFs and receipt emails)
# ---------------------------------------------------------------------------
STORE_NAME = os.getenv('STORE_NAME', 'MODEZA Boutique')
STORE_EMAIL = os.getenv('STORE_EMAIL', 'hello@modeza.co.ke')
STORE_PHONE = os.getenv('STORE_PHONE', '+254 700 123 456')
STORE_WEBSITE = os.getenv('STORE_WEBSITE', 'https://modeza.co.ke')
STORE_ADDRESS = os.getenv('STORE_ADDRESS', 'Nairobi, Kenya')

# ---------------------------------------------------------------------------
# Outbound email (automatic receipts & notifications)
#
# SMTP is activated whenever EMAIL_HOST is set (Render production). Otherwise
# the console backend prints messages to the log — a safe zero-config default
# for local development that can never fail a delivery attempt.
# ---------------------------------------------------------------------------
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.getenv(
        'EMAIL_USE_TLS', 'True').lower() in {'1', 'true', 'yes', 'on'}
    EMAIL_USE_SSL = os.getenv(
        'EMAIL_USE_SSL', 'False').lower() in {'1', 'true', 'yes', 'on'}
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL', f'{STORE_NAME} <receipts@modeza.co.ke>')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'audit.apps.AuditConfig',
    'accounts',
    'admin_api',
    'admin_ui.apps.AdminUiConfig',
    'catalog',
    'cart',
    'inventory',
    'orders',
    'payments',
    'receipts',
    'store',
]

# ---------------------------------------------------------------------------
# Rate limiting / throttling
# ---------------------------------------------------------------------------
# Production defaults are safe for real anonymous traffic.
#
# Load-test mode (LOAD_TEST_MODE=true) keeps the exact same throttle classes
# active but raises the per-IP budgets to levels that tolerate a 500-VU k6 run.
# Every k6 virtual user shares the same 127.0.0.1 address, so the production
# limits (e.g. anon 60/minute *per IP*) are exhausted within seconds and the
# API answers with 429 for the remainder of the run. Load-test budgets treat
# the whole run as one large transient bucket instead.
#
# Each rate can also be overridden per-environment at deployment time, e.g.:
#   THROTTLE_ANON_RATE=300/minute
#   (or LOAD_TEST_ANON_RATE=... while LOAD_TEST_MODE=true)

LOAD_TEST_MODE = os.getenv(
    'LOAD_TEST_MODE', '').lower() in {'1', 'true', 'yes', 'on'}

THROTTLE_RATES = {
    'anon': os.getenv('THROTTLE_ANON_RATE', '60/minute'),
    'user': os.getenv('THROTTLE_USER_RATE', '120/minute'),
    'orders': os.getenv('THROTTLE_ORDERS_RATE', '20/minute'),
    'payments': os.getenv('THROTTLE_PAYMENTS_RATE', '10/minute'),
    'admin': os.getenv('THROTTLE_ADMIN_RATE', '60/minute'),
    'audit': os.getenv('THROTTLE_AUDIT_RATE', '60/minute'),
}

if LOAD_TEST_MODE:
    THROTTLE_RATES = {
        'anon': os.getenv('LOAD_TEST_ANON_RATE', '100000/minute'),
        'user': os.getenv('LOAD_TEST_USER_RATE', '100000/minute'),
        'orders': os.getenv('LOAD_TEST_ORDERS_RATE', '60000/minute'),
        'payments': os.getenv('LOAD_TEST_PAYMENTS_RATE', '30000/minute'),
        'admin': os.getenv('LOAD_TEST_ADMIN_RATE', '60000/minute'),
        'audit': os.getenv('LOAD_TEST_AUDIT_RATE', '60000/minute'),
    }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.SupabaseJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'botique_backend.exceptions.api_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': THROTTLE_RATES,
}

SUPABASE_JWT_SECRET = os.getenv('SUPABASE_JWT_SECRET', '')
SUPABASE_JWT_AUDIENCE = os.getenv('SUPABASE_JWT_AUDIENCE', 'authenticated')
SUPABASE_JWT_ISSUER = os.getenv('SUPABASE_JWT_ISSUER', '')
SUPABASE_JWT_JWKS_URL = os.getenv(
    'SUPABASE_JWT_JWKS_URL',
    f'{SUPABASE_JWT_ISSUER}/.well-known/jwks.json' if SUPABASE_JWT_ISSUER else '',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'botique_backend.middleware.RequestContextMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'botique_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'admin_ui.context_processors.admin_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'botique_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=60,
            conn_health_checks=True,
        )
    }
else:
    # Fallback to SQLite for local development when
    # DATABASE_URL is not set (e.g., local experimentation).
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Admin staff sign in with either their username or their account email.
AUTHENTICATION_BACKENDS = [
    'admin_ui.backends.EmailOrUsernameModelBackend',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SUPABASE_URL = os.getenv('SUPABASE_URL', '').rstrip('/')
SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY', '')
SUPABASE_STORAGE_BUCKET = os.getenv(
    'SUPABASE_STORAGE_BUCKET', 'product-images')

if SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY:
    DEFAULT_STORAGE_BACKEND = 'botique_backend.storage.SupabaseStorage'
    DEFAULT_STORAGE_OPTIONS = {}
else:
    DEFAULT_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'
    DEFAULT_STORAGE_OPTIONS = {'location': MEDIA_ROOT}

# Served by WhiteNoise in production: compressed, hashed, cache-busted assets.
STORAGES = {
    'default': {
        'BACKEND': DEFAULT_STORAGE_BACKEND,
        'OPTIONS': DEFAULT_STORAGE_OPTIONS,
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 365


# Logging — structured console logs with per-request correlation.
# LOG_FORMAT=json emits one JSON object per line (Render console friendly);
# LOG_FORMAT=text keeps the human-readable verbose layout for local dev.
LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')
LOG_FORMAT = os.getenv('LOG_FORMAT', 'text')

# Audit trail retention (days) used by `python manage.py cleanup_audit_logs`.
AUDIT_LOG_RETENTION_DAYS = int(os.getenv('AUDIT_LOG_RETENTION_DAYS', '365'))

# Trust the first X-Forwarded-For entry as the client IP when the app sits
# behind a reverse proxy / load balancer (Render). Keep False on direct hosts.
USE_X_FORWARDED_FOR = os.getenv(
    'USE_X_FORWARDED_FOR', 'False').lower() in {'1', 'true', 'yes', 'on'}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_context': {
            '()': 'botique_backend.logging.RequestContextFilter',
        },
    },
    'formatters': {
        'json': {
            '()': 'botique_backend.logging.JsonFormatter',
        },
        'verbose': {
            '()': 'botique_backend.logging.TextFormatter',
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['request_context'],
            'formatter': 'json' if LOG_FORMAT == 'json' else 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'modeza': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'modeza.http': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'audit': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'payments': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'orders': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'catalog': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'inventory': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'admin_api': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'admin_ui': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'receipts': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}


# Security hardening. The secure-cookie and SSL flags are only meaningful
# behind TLS termination (e.g. Render's load balancer), so they are applied
# only when NOT running in DEBUG mode.
if not DEBUG:
    # Trust the proxy's forwarded protocol (Render/LB terminate TLS).
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = os.getenv(
        'DJANGO_SESSION_COOKIE_SECURE', 'True').lower() in {'1', 'true', 'yes', 'on'}
    CSRF_COOKIE_SECURE = os.getenv(
        'DJANGO_CSRF_COOKIE_SECURE', 'True').lower() in {'1', 'true', 'yes', 'on'}
    SECURE_SSL_REDIRECT = os.getenv(
        'DJANGO_SECURE_SSL_REDIRECT', 'False').lower() in {'1', 'true', 'yes', 'on'}
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'

# Default primary key field type for Django models that do not
# explicitly define one.  The project uses UUID primary keys on
# commerce models; this avoids the Django 3.2+ deprecation warning.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
