# Generated by Django 6.0.7 on 2026-09-21 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('signup', 'Signup'), ('password_reset', 'Password Reset'), ('permission_denied', 'Permission Denied'), ('access_denied', 'Access Denied'), ('status_change', 'Status Change'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('refund', 'Refund'), ('checkout_started', 'Checkout Started'), ('checkout_failed', 'Checkout Failed'), ('file_upload', 'File Upload'), ('file_delete', 'File Delete'), ('server_error', 'Server Error'), ('security_event', 'Security Event')], db_index=True, max_length=32)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('object_type', models.CharField(blank=True, default='', max_length=40)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], db_index=True, default='success', max_length=10)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['created_at', 'severity'], name='audit_audit_created_91069c_idx')],
            },
        ),
    ]
