# Generated by Django 6.1.1 on 2026-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('file_upload', 'File Upload'), ('file_delete', 'File Delete'), ('status_change', 'Status Change'), ('refund', 'Refund'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('signup', 'Signup'), ('customer_registered', 'Customer Registered'), ('registration_failed', 'Registration Failed'), ('password_reset', 'Password Reset'), ('password_updated', 'Password Updated'), ('profile_updated', 'Profile Updated'), ('product_viewed', 'Product Viewed'), ('category_viewed', 'Category Viewed'), ('search_performed', 'Search Performed'), ('cart_item_added', 'Cart Item Added'), ('cart_item_updated', 'Cart Item Updated'), ('cart_item_removed', 'Cart Item Removed'), ('cart_cleared', 'Cart Cleared'), ('cart_add_failed', 'Cart Add Failed'), ('cart_update_failed', 'Cart Update Failed'), ('checkout_started', 'Checkout Started'), ('checkout_failed', 'Checkout Failed'), ('order_created', 'Order Created'), ('order_creation_failed', 'Order Creation Failed'), ('order_details_viewed', 'Order Details Viewed'), ('order_cancelled', 'Order Cancelled'), ('order_confirmed', 'Order Confirmed'), ('order_received', 'Order Received'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_initiation_failed', 'Payment Initiation Failed'), ('payment_timeout', 'Payment Timeout'), ('payment_reversed', 'Payment Reversed'), ('refund_requested', 'Refund Requested'), ('refund_completed', 'Refund Completed'), ('wishlist_item_added', 'Wishlist Item Added'), ('wishlist_item_removed', 'Wishlist Item Removed'), ('wishlist_cleared', 'Wishlist Cleared'), ('review_submitted', 'Review Submitted'), ('support_message_submitted', 'Support Message Submitted'), ('security_event', 'Security Event'), ('permission_denied', 'Permission Denied'), ('access_denied', 'Access Denied'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('server_error', 'Server Error'), ('unexpected_server_error', 'Unexpected Server Error'), ('inventory_low_stock', 'Inventory Low Stock')], db_index=True, max_length=32),
        ),
    ]
